version: 2

models:
  - name: territory2
    description: Territory Table
    columns:
      - name: ID
        description: Primary key
        tests:
          - unique
          - not_null